# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [3]:
df = pd.read_csv('cardekho_imputated.csv',index_col = [0])

In [4]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Cleaning
### Handling Missing values

* Handling Missing values 
* Handling Duplicates
* Check data type
* Understand the dataset

In [5]:
## Check Null Values
## Check features with nan value
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [6]:
## Remove Unnecessary Columns
df.drop('car_name', axis=1, inplace=True)
df.drop('brand', axis=1, inplace=True)

In [7]:
## Getting All Different Types OF Features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))

Num of Numerical Features : 7
Num of Categorical Features : 4
Num of Discrete Features : 2
Num of Continuous Features : 5

In [8]:
## Indpendent and dependent features
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'], axis=1)
y = df['selling_price']

## Feature Encoding and Scaling
**One Hot Encoding for Columns which had lesser unique values and not ordinal**
* One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [9]:
len(df['model'].unique())

120

In [10]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [12]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [13]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [14]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StandardScaler", numeric_transformer, num_features)
        
    ],remainder='passthrough'
    
)

In [15]:
X=preprocessor.fit_transform(X)

In [16]:
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

## Model Training And Model Selection

In [1]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [18]:
##Create a Function to Evaluate Model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [19]:
## Beginning Model Training
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "AdaBoost Regressor" : AdaBoostRegressor()
   
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 553855.6665
- Mean Absolute Error: 268101.6071
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502543.5930
- Mean Absolute Error: 279618.5794
- R2 Score: 0.6645
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 553855.6710
- Mean Absolute Error: 268099.2226
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502542.6696
- Mean Absolute Error: 279614.7461
- R2 Score: 0.6645
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 553856.3160
- Mean Absolute Error: 268059.8015
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502533.8230
- Mean Absolute Error: 279557.2169
- R2 Score: 0.6645
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 325885.9831
- Mean Absolute Error: 91430.9701
- R2 Score: 0.8691
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 253071.9428
- Mean Absolute Error: 112672.8917
- R2 Score: 0.9149
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 20797.2352
- Mean Absolute Error: 5164.8199
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 308627.3256
- Mean Absolute Error: 125472.5295
- R2 Score: 0.8735
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 132198.7568
- Mean Absolute Error: 39584.0848
- R2 Score: 0.9785
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 230848.6862
- Mean Absolute Error: 101993.8363
- R2 Score: 0.9292
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 494183.2643
- Mean Absolute Error: 388054.2120
- R2 Score: 0.6989
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 559671.8353
- Mean Absolute Error: 407775.1832
- R2 Score: 0.5839
===================================

In [20]:
#Initialize few parameter for Hyperparamter tuning
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

ada_params = {
    "n_estimators" : [50,60,70,80],
    "loss" : ['linear', 'square' , 'exponential']
}

In [21]:
# Models list for Hyperparameter tuning
randomcv_models = [('KNN', KNeighborsRegressor(), knn_params),
                   ("RF", RandomForestRegressor(), rf_params),
                   ("AB", AdaBoostRegressor(), ada_params)
                   
                   ]

In [22]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
[CV] END ......................................n_neighbors=3; total time=   0.6s
[CV] END ......................................n_neighbors=3; total time=   0.8s
[CV] END ......................................n_neighbors=3; total time=   0.9s
[CV] END ......................................n_neighbors=2; total time=   0.9s
[CV] END .....................................n_neighbors=10; total time=   1.2s
[CV] END ......................................n_neighbors=2; total time=   1.2s
[CV] END ......................................n_neighbors=2; total time=   1.1s
[CV] END .....................................n_neighbors=10; total time=   1.4s
[CV] END .....................................n_neighbors=20; total time=   1.5s
[CV] END .....................................n_neighbors=10; total time=   2.3s
[CV] END .....................................n_neighbors=20; total time=   1.7s
[CV] END .....................................n_neighbors=20; total time=   1.9s
[CV] END .....................................n_neighbors=40; total time=   2.0s
[CV] END .....................................n_neighbors=40; total time=   2.0s
[CV] END .....................................n_neighbors=50; total time=   1.6s
[CV] END .....................................n_neighbors=40; total time=   2.5s
[CV] END .....................................n_neighbors=50; total time=   1.7s
[CV] END .....................................n_neighbors=50; total time=   1.7s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=  19.6s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=  22.6s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=500; total time=  24.0s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=  24.9s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=500; total time=  25.4s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=  26.2s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100; total time=   2.8s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=  28.7s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100; total time=   4.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=  31.8s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100; total time=   3.6s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=8, min_samples_split=20, n_estimators=500; total time=  19.7s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=  13.0s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=500; total time=  18.5s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=  14.9s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=500; total time=  19.8s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=500; total time=  23.2s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=  15.3s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   8.3s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   8.9s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=  10.4s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=100; total time=   7.0s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=100; total time=   7.8s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=100; total time=   7.7s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=  36.1s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   8.2s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=  33.3s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   5.4s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=200; total time=   7.3s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100; total time=   2.1s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100; total time=   2.2s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=  35.9s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   9.1s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   7.9s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100; total time=   2.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   8.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   3.5s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   3.5s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   3.5s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=  41.4s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=  45.7s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=1000; total time=  43.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=  17.4s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=  18.5s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=  20.1s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=200; total time=   5.4s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=200; total time=   6.2s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=200; total time=   6.9s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=  17.5s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  36.5s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=  43.1s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=  17.9s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   2.5s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   3.7s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=  44.7s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   5.2s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  39.2s
[CV] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=1000; total time=  39.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=  48.2s
[CV] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=500; total time=  15.6s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   3.9s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   3.8s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=100; total time=   4.0s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=200; total time=   6.0s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=200; total time=   4.9s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=  18.6s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=  19.7s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=  19.3s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=500; total time=  19.2s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   1.8s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=200; total time=   5.5s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=500; total time=  19.5s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   1.8s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   2.6s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=500; total time=  20.9s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   8.1s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=   8.8s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=200; total time=  10.6s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=  22.8s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=  24.9s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=  13.3s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=  13.1s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=  29.6s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=  13.4s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=  11.8s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=  12.0s
[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500; total time=  13.5s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  37.5s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  37.7s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   7.1s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   7.9s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   5.5s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   7.6s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=500; total time=  22.6s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=500; total time=  19.0s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   8.9s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   7.9s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=  46.2s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=500; total time=  20.4s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   2.2s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   1.8s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   7.1s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   8.6s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=200; total time=   8.0s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=500; total time=  18.7s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=500; total time=  19.1s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   8.8s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=500; total time=  19.5s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   9.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=500; total time=   9.2s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.7s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   2.4s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   2.4s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   7.5s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=200; total time=   6.4s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=200; total time=   5.6s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   7.0s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   8.1s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=200; total time=   6.1s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   6.4s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   6.0s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=200; total time=   6.8s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  32.5s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000; total time=  17.0s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000; total time=  17.8s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000; total time=  19.4s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  35.1s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  34.6s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=  15.4s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=  19.0s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=  15.8s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=  16.9s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=  14.3s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=  15.8s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   4.1s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   3.4s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100; total time=   3.4s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=200; total time=   7.2s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=200; total time=   9.3s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=200; total time=   8.7s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=  10.3s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=  13.8s
[CV] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=500; total time=  11.9s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=500; total time=  20.2s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=500; total time=  24.6s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=500; total time=  22.3s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   3.6s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   4.2s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   3.3s
[CV] END max_depth=8, max_features=5, min_samples_split=20, n_estimators=1000; total time=  20.7s

In [24]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=1000, min_samples_split=2, max_features=8, max_depth=None, 
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=10, n_jobs=-1),
     "Adaboost Regressor" : AdaBoostRegressor(n_estimators = 50 , loss="linear")
    
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 129716.0486
- Mean Absolute Error: 38910.2667
- R2 Score: 0.9793
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 214093.8319
- Mean Absolute Error: 98413.4190
- R2 Score: 0.9391
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 363465.6927
- Mean Absolute Error: 103489.6090
- R2 Score: 0.8371
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 263849.8119
- Mean Absolute Error: 117481.4548
- R2 Score: 0.9075
===================================


Adaboost Regressor
Model performance for Training set
- Root Mean Squared Error: 407997.5111
- Mean Absolute Error: 260323.0619
- R2 Score: 0.7948
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 443454.3327
- Mean Absolute Error: 277987.1881
- R2 Score: 0.7388
===================================